name: lint

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  selene:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: Kampfkarren/selenology@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config selene.toml --color always ./lua
